annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "changed links to get a better overview of sources"
    - kind: fixed
      description: "Updated all instances of the caCerts enabled check"
    - kind: changed
      description: "changed description of dependency postgresql chart"
    - kind: changed
      description: "no longer automount service account token"
    - kind: changed
      description: "secure admin password in k8s secret"
    - kind: changed
      description: "Specify service account name in change admin password hook"
    - kind: fixed
      description: "Specify location of .netrc file when downloading plugins that require auth"
    - kind: changed
      description: "updated SonarQube to 9.4.0"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/images: |
    - name: sonarqube
      image: sonarqube:9.4.0-community
  artifacthub.io/links: |
    - name: support
      url: https://community.sonarsource.com/
    - name: Chart Source
      url: https://github.com/SonarSource/helm-chart-sonarqube/tree/master/charts/sonarqube
apiVersion: v1
appVersion: 9.4.0
description: SonarQube offers Code Quality and Code Security analysis for up to 27
  languages. Find Bugs, Vulnerabilities, Security Hotspots and Code Smells throughout
  your workflow.
home: https://www.sonarqube.org/
icon: https://www.sonarqube.org/assets/logo-31ad3115b1b4b120f3d1efd63e6b13ac9f1f89437f0cf6881cc4d8b5603a52b4.svg
keywords:
- coverage
- security
- code
- quality
kubeVersion: '>= 1.19.0-0'
maintainers:
- email: leo.geoffroy+helm@sonarsource.com
  name: leo-geoffroy-sonarsource
name: sonarqube
sources:
- https://github.com/SonarSource/docker-sonarqube
- https://github.com/SonarSource/sonarqube
version: 3.0.0+296
